# Generated by Django 3.1.1 on 2020-09-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kouka2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=1000)),
                ('area', models.CharField(max_length=1000)),
                ('delivery', models.CharField(max_length=1000)),
                ('price', models.IntegerField(default=0)),
                ('attachment', models.CharField(max_length=1000)),
            ],
        ),
    ]
